(() => {
  'use strict';
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const count = v => v == null ? '확인 전' : `${Number(v).toLocaleString('ko-KR')}실`;
  const money = v => v == null ? '가격 없음' : `${Number(v).toLocaleString('ko-KR')}원`;
  const types = {lodging:'숙박',dayuse:'데이유즈',unknown:'구분 확인 전'};
  const statuses = {dispatching:'접수 확인',queued:'수집 대기',collecting:'수집 대기·진행 중',ready:'완료',partial:'일부 완료',blocked:'접근 제한',failed:'실패',needs_review:'확인 필요'};
  const active = r => ['dispatching','queued','collecting'].includes(r?.status);
  let api, companyId, view = null, serial = 0, timer, renderedVersion, loadOrder=0;
  const date = () => new Date(Date.now()+9*3600000).toISOString().slice(0,10);
  function panel(company, enabled, request) {
    const intent=request?.intent || {}, start=intent.checkIn>=date()?intent.checkIn:date(), days=intent.bookingRangeDays || 31, mode=intent.dayUseMode || 'inspect';
    return `<section class="card collection-setup"><span class="eyebrow">COLLECTION</span><h1>${esc(company.name)} 자료 수집</h1><p class="muted">객실·상품을 확인하고 잘못된 정보를 수정 요청할 수 있습니다. 오늘 같은 업체·조건의 자료가 있으면 다시 수집하지 않고 연결합니다.</p><form data-collect="${esc(company.companyId)}"><div class="form-grid collection-fields"><label class="field"><span>숙박 시작일</span><input name="checkIn" type="date" min="${date()}" value="${esc(start)}" required></label><label class="field"><span>조회 기간</span><select name="bookingRangeDays">${[1,7,14,31].map(n=>`<option value="${n}" ${days===n?'selected':''}>${n}일</option>`).join('')}</select></label><label class="field"><span>데이유즈</span><select name="dayUseMode">${Object.entries({inspect:'유무 확인',lodging_only:'숙박만',detail:'상세 수집'}).map(([v,n])=>`<option value="${v}" ${mode===v?'selected':''}>${n}</option>`).join('')}</select></label></div><p class="muted">유무 확인은 상품 존재 여부를 확인합니다. 데이유즈 날짜별 수량은 상세 수집에서 확인할 수 있습니다.</p><button class="button primary" type="submit" data-ready="${enabled}" ${enabled?'':'disabled'}>수집하기</button>${enabled?'':'<p class="muted">수집기 연결을 준비 중입니다.</p>'}</form></section><section id="collection-progress" class="collection-progress" aria-live="polite"></section><section id="collection-result" aria-label="객실 및 상품 수집 결과"><p role="status">저장된 결과를 불러옵니다.</p></section>`;
  }
  function progress(data) {
    const r=data?.request;
    const target=document.querySelector('#collection-progress'); if(!target)return;
    target.innerHTML=r?`<div class="collection-status ${active(r)?'running':''}"><span class="activity-dot" aria-hidden="true"></span><strong>${esc(statuses[r.status]||'상태 확인')}</strong><span>${esc(r.message)}</span><button type="button" class="button small" data-action="refresh-collection">새로고침</button></div><p class="muted">접수 ${esc(new Date(r.submittedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))}${r.errorCode?` · 원인 코드 ${esc(r.errorCode)}`:''}</p>`:'';
    const submit=document.querySelector('[data-collect] button[type=submit]'); if(submit)submit.disabled=active(r)||submit.dataset.ready!=='true';
  }
  function renderResult(data) {
    const r=data.result;
    if(!r)return '<div class="empty-note">아직 연결할 객실·상품 결과가 없습니다. 수집 후 이곳에서 확인할 수 있습니다.</div>';
    const source=r.roomCountSource || '수집 기반 추정';
    return `${data.previousResult?'<p class="collection-warning">아래는 이전에 저장된 자료입니다. 이번 요청의 완료 결과가 아닙니다.</p>':''}<div class="collection-summary"><article><span>객실 총량</span><strong>${count(r.rooms)}</strong><small>${esc(source)}${r.originalRooms!=null?` · 이번 관측 최대 ${count(r.originalRooms)}`:''}</small></article><article><span>상품 종류</span><strong>${r.productCount}개</strong><small>상품 개수는 객실 수와 다릅니다.</small></article><article><span>숙박 조회 기간</span><strong>${esc(r.range.days ?? '?')}일</strong><small>${esc(r.range.start||'날짜 확인 전')} ~ ${esc(r.range.end||'확인 전')}</small></article></div><p class="muted">데이유즈: ${esc({present:'상품 있음',absent:'상품 없음',unknown:'확인 전'}[r.dayUse?.presence]||'확인 전')} · 객실 공유: ${esc({confirmed:'공유 확인',shared:'공유 확인',separate:'별도 객실',confirmed_separate:'별도 객실',not_shared:'별도 객실'}[r.dayUse?.sharing]||'확인 전')}</p><p class="muted">수집 ${r.collectedAt?esc(new Date(r.collectedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})):'시각 확인 전'} · ${esc(r.runId)}</p>${r.quality.status!=='complete'?`<p class="collection-warning">${esc(statuses[r.quality.status]||'품질 확인 필요')} · ${esc(r.quality.reason)}</p>`:''}${r.capacityWarning?`<p class="collection-warning capacity-warning">객실 수 검토 필요 · ${esc(r.capacityWarning)}</p>`:''}${r.issues.length?`<details class="collection-warning"><summary>확인하지 못한 자료 ${r.issues.length}건</summary><ul>${r.issues.map(i=>`<li>${esc(i.productName)} · ${esc(i.label||i.code)} ${esc(i.dates.join(', '))}</li>`).join('')}</ul></details>`:''}<div class="collection-legend"><span class="public-value">● 공개 예약</span><span class="estimated-value">● 방막기 추정</span><span>오류·누락은 수량 0으로 계산하지 않습니다.</span></div>${r.days.length?`<details class="collection-daily"><summary>날짜별 예약·추정매출</summary><p class="muted">공개 예약의 계산 매출과 방막기 추정 매출입니다. 실제 결제 매출과 다를 수 있습니다. 공유 데이유즈 제외 수량은 기존 검수 기준을 적용합니다.</p><div class="collection-table-wrap"><table><caption class="sr-only">숙박일별 예약과 추정매출</caption><thead><tr><th>숙박일 / 구분</th><th>예약 가능</th><th>공개 예약</th><th>공개 예약 매출</th><th>방막기 추정</th><th>방막기 추정 매출</th><th>공유 제외</th></tr></thead><tbody>${r.days.map(d=>`<tr><th>${esc(d.date)}<small>${esc(types[d.productType]||'구분 확인')} ${d.status!=='observed'?'· 일부 확인 필요':''}</small></th><td>${count(d.available)}</td><td class="public-value">${count(d.publicBookings)}</td><td class="public-value">${money(d.publicRevenue)}</td><td class="estimated-value">${count(d.estimatedBlocked)}</td><td class="estimated-value">${money(d.estimatedRevenue)}</td><td>${count(d.sharedDayUseExcluded)}</td></tr>`).join('')}</tbody></table></div></details>`:''}<h2 class="collection-product-heading">객실·상품 ${r.productCount}개</h2><p class="muted">상품을 펼치면 날짜별 수량과 숙박 객실 판매금액을 확인할 수 있습니다.</p>${r.truncated?'<p class="collection-warning">보존된 상품 목록이 일부만 남아 있습니다.</p>':''}<div class="collection-products">${r.products.map((p,index)=>productCard(p,index,r)).join('')||'<p class="empty-note">상품 상세 자료가 없습니다.</p>'}</div>`;
  }
  function productCard(p,index,r) {
    const quantities=p.days.map(d=>d.total).filter(v=>v!==null),prices=p.days.map(d=>d.price).filter(v=>v!==null);
    return `<details class="collection-product"><summary><span>${esc(p.name)}</span><span class="status-pill">${esc(types[p.productType])}</span><small>${p.days.length}일 관측</small></summary><p class="muted">최대 공개 재고 ${quantities.length?count(Math.max(...quantities)):'확인 전'} · ${prices.length?money(Math.min(...prices)):'가격 확인 전'}${prices.length&&Math.max(...prices)!==Math.min(...prices)?` ~ ${money(Math.max(...prices))}`:''}</p><details class="product-days"><summary>날짜별 수량·판매금액 보기</summary><div class="collection-table-wrap"><table><thead><tr><th>숙박일</th><th>응답</th><th>공개 재고</th><th>예약 가능</th><th>공개 예약</th><th>${p.productType==='lodging'?'숙박 객실 판매금액':'상품 판매금액'}</th></tr></thead><tbody>${p.days.map(d=>`<tr><th>${esc(d.date||'날짜 확인 전')}</th><td>${esc({observed:'정상 응답',error:'오류·차단',missing:'자료 누락',not_requested:'유무만 확인'}[d.status])}${d.errorCode?`<small>${esc(d.errorCode)}</small>`:''}${d.saleStatus==='closure_unconfirmed'?'<small>판매중지 미확정</small>':''}</td><td>${count(d.total)}${p.original.find(o=>o.date===d.date)?.total!=null&&p.original.find(o=>o.date===d.date).total!==d.total?`<small>수집값 ${count(p.original.find(o=>o.date===d.date).total)} · DB 검수 적용</small>`:''}</td><td>${count(d.available)}</td><td class="public-value">${count(d.publicBookings)}</td><td>${money(d.price)}</td></tr>`).join('')}</tbody></table></div></details><details class="product-edit"><summary>이 상품 정보 수정 요청</summary><form data-product-correction="${index}"><p class="muted">요청은 검수 후 반영합니다. 전체 객실 수는 아래 ‘업체 정보 수정’에서 수정하세요.</p><div class="form-grid"><label class="field"><span>적용할 숙박일</span><select name="date" required>${p.days.filter(d=>d.date).map(d=>`<option value="${esc(d.date)}">${esc(d.date)} · ${count(d.total)} (${esc(d.status==='observed'?'정상':'수량 보정 불가')})</option>`).join('')}</select></label><label class="field"><span>객실 수 보정 제안</span><input type="number" name="total" min="1" max="10000" step="1" placeholder="변경할 때만 입력"></label><label class="field"><span>상품 구분</span><select name="productType">${Object.entries(types).map(([v,n])=>`<option value="${v}" ${v===p.productType?'selected':''}>${n}</option>`).join('')}</select></label></div><label class="field"><span>변경 근거</span><textarea name="reason" required maxlength="1000" placeholder="객실 구성, 공식 안내, 확인 날짜 등을 적어 주세요."></textarea></label><button class="button" type="submit">상품 검수 요청 보내기</button></form></details></details>`;
  }
  async function load(force=false) {
    const mine=serial, id=companyId, order=++loadOrder;
    clearTimeout(timer);
    try {
      const data=await api(`/companies/${encodeURIComponent(id)}/collection`);
      if(mine!==serial || order!==loadOrder || !document.querySelector('#collection-result'))return;
      progress(data);
      const version=JSON.stringify([data.result?.version,data.previousResult]);
      if(force || renderedVersion!==version) {
        if(!force && document.querySelector('#collection-result form:focus-within, #collection-result form[data-dirty]')) { const note=document.createElement('p'); note.className='muted';note.textContent='새 결과가 있습니다. 작성 중인 내용을 유지했습니다. 새로고침하면 최신 결과를 표시합니다.';document.querySelector('#collection-progress').append(note); if(active(data.request))timer=setTimeout(()=>load(),10000); return; }
        view=data;renderedVersion=version;document.querySelector('#collection-result').innerHTML=renderResult(data);
      }
      if(active(data.request))timer=setTimeout(()=>{if(!document.hidden)load();else timer=setTimeout(()=>load(),10000);},5000);
    } catch(error) { if(mine===serial && document.querySelector('#collection-progress'))document.querySelector('#collection-progress').innerHTML=`<p class="collection-warning">${esc(error.message)} <button class="button small" data-action="refresh-collection">다시 확인</button></p>`; }
  }
  window.InsightCollection={panel, mount(id,request){serial++;clearTimeout(timer);companyId=id;api=request;view=null;renderedVersion=null;load();},stop(){serial++;clearTimeout(timer);},refresh:()=>load(true),
    correction(index,p){const r=view?.result, product=r?.products[Number(index)];if(!product)throw Error('수집 결과를 다시 열어 주세요.');const proposed={};if(p.total!=='')proposed.total=Number(p.total);if(p.productType!==product.productType)proposed.productType=p.productType;return {companyId,baseVersion:r.version,target:{runId:r.runId,productKey:product.key,date:p.date},proposed,reason:p.reason};}};
})();
