"use strict";

const NAVER_PROVIDER_ID = "naver_place_search";
const PROVIDER_HEALTH_SCHEMA_VERSION = 1;
const COOLDOWN_POLICY_VERSION = "naver-place-cooldown-v1";
const PUBLIC_BLOCK_CODE = "NAVER_ACCESS_BLOCKED";
const MAX_COOLDOWN_SECONDS = 120 * 60;
const DEFAULT_429_COOLDOWN_SECONDS = 15 * 60;
const DEFAULT_ACCESS_BLOCK_COOLDOWN_SECONDS = 30 * 60;
const PROVIDER_ATTEMPT_LEASE_SECONDS = 30 * 60;
const PROVIDER_ATTEMPT_HEARTBEAT_SECONDS = 60;
const PROBE_ESCALATION_SECONDS = Object.freeze([30 * 60, 60 * 60, 120 * 60]);
const PROVIDER_STATES = Object.freeze(["closed", "open", "probe_allowed"]);
const PROVIDER_OUTCOME_KINDS = Object.freeze(["success", "block", "release"]);
const OUTCOME_RECEIPT_PATTERN = /^[a-f0-9]{64}$/u;
const FAILURE_SUBTYPES = Object.freeze([
  "http_403",
  "http_429",
  "challenge_html",
  "unknown_access_block"
]);
const APOLLO_MARKERS = Object.freeze([
  "window.__APOLLO_STATE__ = ",
  "window.__APOLLO_STATE__=",
  "__APOLLO_STATE__ = ",
  "__APOLLO_STATE__="
]);
const CHALLENGE_PATTERN = /captcha|wtmcaptcha|ncpt\.naver\.com|access\s*denied|sorry,?\s*you\s*have\s*been\s*blocked|비정상적인\s*접근|자동입력\s*방지|보안\s*확인/i;

function canonicalInstant(value, label = "timestamp") {
  const date = value instanceof Date ? new Date(value.getTime()) : new Date(value);
  if (!Number.isFinite(date.getTime())) throw new TypeError(`${label} must be a valid instant`);
  return date.toISOString();
}

function responseStatus(input) {
  const candidate = input?.status ?? input?.statusCode ?? input?.response?.status;
  const status = Number(candidate);
  return Number.isInteger(status) && status >= 100 && status <= 599 ? status : null;
}

function headerValue(headers, name) {
  if (!headers) return null;
  if (typeof headers.get === "function") return headers.get(name);
  if (typeof headers !== "object" || Array.isArray(headers)) return null;
  const key = Object.keys(headers).find((candidate) => candidate.toLowerCase() === name.toLowerCase());
  const value = key ? headers[key] : null;
  return Array.isArray(value) ? value[0] : value;
}

function parseSafeRetryAfter(value, options = {}) {
  if (Array.isArray(value)) value = value[0];
  if (typeof value !== "string" && typeof value !== "number") return null;
  const source = String(value).trim();
  if (!source || source.length > 128) return null;
  const configuredMax = Number(options.maxSeconds);
  const maxSeconds = Number.isInteger(configuredMax) && configuredMax >= 0
    ? Math.min(configuredMax, MAX_COOLDOWN_SECONDS)
    : MAX_COOLDOWN_SECONDS;

  if (/^\d+$/.test(source)) {
    const seconds = Number(source);
    if (!Number.isSafeInteger(seconds)) return maxSeconds;
    return Math.min(seconds, maxSeconds);
  }

  // Retry-After HTTP dates are deliberately limited to the IMF-fixdate form.
  // This accepts the form generated by standard HTTP servers without treating
  // arbitrary date-like text as scheduling instructions.
  if (!/^(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun), \d{2} (?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4} \d{2}:\d{2}:\d{2} GMT$/.test(source)) {
    return null;
  }
  const retryAt = Date.parse(source);
  if (!Number.isFinite(retryAt) || new Date(retryAt).toUTCString() !== source) return null;
  const now = options.now instanceof Date
    ? options.now.getTime()
    : options.now == null
      ? Date.now()
      : new Date(options.now).getTime();
  if (!Number.isFinite(now)) throw new TypeError("Retry-After now must be a valid instant");
  return Math.min(Math.max(0, Math.ceil((retryAt - now) / 1000)), maxSeconds);
}

function bodyText(input) {
  const value = input?.body ?? input?.text ?? input?.responseBody ?? "";
  if (Buffer.isBuffer(value)) return value.toString("utf8");
  return String(value || "");
}

function hasApolloMarker(source, input) {
  if (input?.apolloStateValidated === false) return false;
  if (input?.apolloStateValidated === true) return true;
  if (input?.hasApolloState === true || input?.apolloStateFound === true) return true;
  const lowered = source.toLowerCase();
  return APOLLO_MARKERS.some((marker) => lowered.includes(marker.toLowerCase()));
}

function looksLikeHtmlResponse(input, source) {
  const contentType = String(headerValue(input?.headers ?? input?.response?.headers, "content-type") || "").toLowerCase();
  if (/^(?:text\/html|application\/xhtml\+xml)(?:\s*;|$)/.test(contentType)) return true;
  const prefix = String(source || "").trimStart().slice(0, 4096);
  return /^(?:<!doctype\s+html\b|<(?:html|head|body|script|div|main|form|section|meta|title)\b)/i.test(prefix);
}

function classifyNaverAccessResponse(input = {}, options = {}) {
  const status = responseStatus(input);
  const source = bodyText(input);
  const retryAfterValue = input.retryAfter
    ?? headerValue(input.headers ?? input.response?.headers, "retry-after");
  const retryAfterSeconds = parseSafeRetryAfter(retryAfterValue, {
    now: options.now ?? input.observedAt,
    maxSeconds: options.maxRetryAfterSeconds
  });

  let subtype = null;
  if (status === 403) subtype = "http_403";
  else if (status === 429) subtype = "http_429";
  else if (
    looksLikeHtmlResponse(input, source)
    && !hasApolloMarker(source, input)
    && CHALLENGE_PATTERN.test(source)
  ) subtype = "challenge_html";
  else if (input.accessBlocked === true) subtype = "unknown_access_block";

  return Object.freeze({
    blocked: subtype !== null,
    code: subtype === null ? null : PUBLIC_BLOCK_CODE,
    subtype,
    httpStatus: status,
    retryAfterSeconds: subtype === "http_429" ? retryAfterSeconds : null
  });
}

function safeDiagnosticId(value) {
  const diagnosticId = String(value || "");
  return /^crawl-[a-f0-9]{12}$/.test(diagnosticId) ? diagnosticId : null;
}

function sanitizeProviderFailureMeta(value = {}, options = {}) {
  const subtype = FAILURE_SUBTYPES.includes(value.subtype)
    ? value.subtype
    : "unknown_access_block";
  const status = Number(value.httpStatus ?? value.status ?? value.statusCode);
  const httpStatus = Number.isInteger(status) && status >= 100 && status <= 599 ? status : null;
  const retryAfterSeconds = subtype === "http_429"
    ? parseSafeRetryAfter(value.retryAfterSeconds ?? value.retryAfter, {
      now: options.now ?? value.occurredAt,
      maxSeconds: options.maxRetryAfterSeconds
    })
    : null;
  const occurredAt = canonicalInstant(options.occurredAt ?? value.occurredAt ?? options.now ?? new Date(), "occurredAt");

  return Object.freeze({
    providerId: NAVER_PROVIDER_ID,
    code: PUBLIC_BLOCK_CODE,
    subtype,
    httpStatus,
    retryAfterSeconds,
    occurredAt,
    diagnosticId: safeDiagnosticId(value.diagnosticId)
  });
}

function createInitialProviderCircuitState(options = {}) {
  const now = canonicalInstant(options.now ?? new Date(), "now");
  return Object.freeze({
    schemaVersion: PROVIDER_HEALTH_SCHEMA_VERSION,
    providerId: NAVER_PROVIDER_ID,
    state: "closed",
    openedAt: null,
    retryAt: null,
    consecutiveBlocks: 0,
    lastFailureSubtype: null,
    lastDiagnosticId: null,
    lastAttemptAt: null,
    lastSuccessAt: null,
    lastOutcomeKind: null,
    lastOutcomeReceiptHash: null,
    cooldownPolicyVersion: COOLDOWN_POLICY_VERSION,
    workflowRevision: 0,
    updatedAt: now
  });
}

function isCanonicalInstant(value) {
  if (typeof value !== "string") return false;
  const parsed = new Date(value);
  return Number.isFinite(parsed.getTime()) && parsed.toISOString() === value;
}

function validateProviderCircuitState(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const requiredKeys = [
    "schemaVersion",
    "providerId",
    "state",
    "openedAt",
    "retryAt",
    "consecutiveBlocks",
    "lastFailureSubtype",
    "lastDiagnosticId",
    "lastAttemptAt",
    "lastSuccessAt",
    "cooldownPolicyVersion",
    "workflowRevision",
    "updatedAt"
  ];
  const optionalKeys = ["lastOutcomeKind", "lastOutcomeReceiptHash"];
  const allowedKeys = new Set([...requiredKeys, ...optionalKeys]);
  if (!requiredKeys.every((key) => Object.prototype.hasOwnProperty.call(value, key))) return false;
  if (Object.keys(value).some((key) => !allowedKeys.has(key))) return false;
  const hasOutcomeKind = Object.prototype.hasOwnProperty.call(value, "lastOutcomeKind");
  const hasOutcomeReceipt = Object.prototype.hasOwnProperty.call(value, "lastOutcomeReceiptHash");
  if (hasOutcomeKind !== hasOutcomeReceipt) return false;
  if (value.schemaVersion !== PROVIDER_HEALTH_SCHEMA_VERSION) return false;
  if (value.providerId !== NAVER_PROVIDER_ID) return false;
  if (!PROVIDER_STATES.includes(value.state)) return false;
  if (value.cooldownPolicyVersion !== COOLDOWN_POLICY_VERSION) return false;
  if (!Number.isInteger(value.consecutiveBlocks) || value.consecutiveBlocks < 0) return false;
  if (!Number.isInteger(value.workflowRevision) || value.workflowRevision < 0) return false;
  if (!isCanonicalInstant(value.updatedAt)) return false;
  for (const field of ["openedAt", "retryAt", "lastAttemptAt", "lastSuccessAt"]) {
    if (value[field] !== null && !isCanonicalInstant(value[field])) return false;
  }
  if (value.lastFailureSubtype !== null && !FAILURE_SUBTYPES.includes(value.lastFailureSubtype)) return false;
  if (value.lastDiagnosticId !== null && !safeDiagnosticId(value.lastDiagnosticId)) return false;
  if (hasOutcomeKind) {
    const noOutcomeReceipt = value.lastOutcomeKind === null && value.lastOutcomeReceiptHash === null;
    const validOutcomeReceipt = PROVIDER_OUTCOME_KINDS.includes(value.lastOutcomeKind)
      && OUTCOME_RECEIPT_PATTERN.test(String(value.lastOutcomeReceiptHash || ""));
    if (!noOutcomeReceipt && !validOutcomeReceipt) return false;
  }
  const hasIncidentWindow = value.openedAt !== null || value.retryAt !== null || value.consecutiveBlocks > 0;
  if (value.state === "closed" && (
    hasIncidentWindow
    || value.lastFailureSubtype !== null
    || value.lastDiagnosticId !== null
  )) return false;
  if (value.state === "open" && (
    !value.openedAt
    || !value.retryAt
    || !value.lastAttemptAt
    || value.consecutiveBlocks < 1
    || value.lastFailureSubtype === null
    || Date.parse(value.retryAt) < Date.parse(value.openedAt)
  )) return false;
  if (value.state === "probe_allowed") {
    if (!value.lastAttemptAt) return false;
    if (hasIncidentWindow) {
      if (!value.openedAt || !value.retryAt || value.consecutiveBlocks < 1 || value.lastFailureSubtype === null) return false;
      if (Date.parse(value.retryAt) < Date.parse(value.openedAt)) return false;
    } else if (value.lastFailureSubtype !== null || value.lastDiagnosticId !== null) {
      return false;
    }
  }
  return true;
}

function assertProviderCircuitState(value) {
  if (!validateProviderCircuitState(value)) {
    const error = new Error("NAVER provider circuit state failed validation");
    error.code = "NAVER_PROVIDER_STATE_INVALID";
    error.statusCode = 500;
    throw error;
  }
  return value;
}

function revisionConflict(expected, actual) {
  const error = new Error("NAVER provider workflow revision conflict");
  error.code = "NAVER_PROVIDER_WORKFLOW_REVISION_CONFLICT";
  error.statusCode = 409;
  error.expectedWorkflowRevision = expected;
  error.actualWorkflowRevision = actual;
  return error;
}

function assertExpectedRevision(state, expectedWorkflowRevision) {
  if (expectedWorkflowRevision == null) return;
  if (!Number.isInteger(expectedWorkflowRevision) || expectedWorkflowRevision < 0) {
    throw new TypeError("expectedWorkflowRevision must be a non-negative integer");
  }
  if (state.workflowRevision !== expectedWorkflowRevision) {
    throw revisionConflict(expectedWorkflowRevision, state.workflowRevision);
  }
}

function assertReservedAttempt(state) {
  if (state.state === "probe_allowed") return;
  const error = new Error("NAVER provider attempt must be reserved before recording its outcome");
  error.code = "NAVER_PROVIDER_ATTEMPT_NOT_RESERVED";
  error.statusCode = 409;
  throw error;
}

function nextState(state, updates, now) {
  const next = Object.freeze({
    ...state,
    ...updates,
    workflowRevision: state.workflowRevision + 1,
    updatedAt: canonicalInstant(now, "now")
  });
  return assertProviderCircuitState(next);
}

function outcomeReceiptUpdates(kind, value) {
  if (value == null || value === "") {
    return Object.freeze({ lastOutcomeKind: null, lastOutcomeReceiptHash: null });
  }
  const receiptHash = String(value);
  if (!PROVIDER_OUTCOME_KINDS.includes(kind) || !OUTCOME_RECEIPT_PATTERN.test(receiptHash)) {
    throw new TypeError("provider outcome receipt is invalid");
  }
  return Object.freeze({ lastOutcomeKind: kind, lastOutcomeReceiptHash: receiptHash });
}

function computeProviderCooldownSeconds({ subtype, retryAfterSeconds, consecutiveBlocks } = {}) {
  const count = Number.isInteger(consecutiveBlocks) && consecutiveBlocks > 0 ? consecutiveBlocks : 1;
  if (subtype === "http_429" && Number.isInteger(retryAfterSeconds) && retryAfterSeconds >= 0) {
    return Math.min(retryAfterSeconds, MAX_COOLDOWN_SECONDS);
  }
  if (count === 1 && subtype === "http_429") return DEFAULT_429_COOLDOWN_SECONDS;
  return PROBE_ESCALATION_SECONDS[Math.min(count - 1, PROBE_ESCALATION_SECONDS.length - 1)]
    ?? DEFAULT_ACCESS_BLOCK_COOLDOWN_SECONDS;
}

function beginProviderAttempt(state, options = {}) {
  assertProviderCircuitState(state);
  assertExpectedRevision(state, options.expectedWorkflowRevision);
  const nowIso = canonicalInstant(options.now ?? new Date(), "now");
  const now = Date.parse(nowIso);

  if (state.state === "probe_allowed") {
    const leaseRetryAt = new Date(Date.parse(state.updatedAt) + PROVIDER_ATTEMPT_LEASE_SECONDS * 1000).toISOString();
    const leaseExpired = now >= Date.parse(leaseRetryAt);
    if (!leaseExpired) {
      return Object.freeze({
        allowed: false,
        reason: "probe_in_flight",
        attemptKind: null,
        state,
        retryAt: leaseRetryAt
      });
    }
    const interruptedProbe = Boolean(state.openedAt && state.retryAt && state.consecutiveBlocks > 0);
    if (interruptedProbe && options.explicit !== true) {
      return Object.freeze({
        allowed: false,
        reason: "explicit_probe_required",
        attemptKind: null,
        state,
        retryAt: state.retryAt
      });
    }
    const attemptKind = interruptedProbe ? "probe" : "normal";
    const reserved = nextState(state, {
      lastAttemptAt: nowIso,
      ...outcomeReceiptUpdates(null, null)
    }, nowIso);
    return Object.freeze({
      allowed: true,
      reason: "stale_attempt_recovered",
      attemptKind,
      state: reserved,
      retryAt: interruptedProbe ? reserved.retryAt : null
    });
  }
  if (state.state === "open") {
    if (now < Date.parse(state.retryAt)) {
      return Object.freeze({
        allowed: false,
        reason: "cooldown_active",
        attemptKind: null,
        state,
        retryAt: state.retryAt
      });
    }
    if (options.explicit !== true) {
      return Object.freeze({
        allowed: false,
        reason: "explicit_probe_required",
        attemptKind: null,
        state,
        retryAt: state.retryAt
      });
    }
  }

  const attemptKind = state.state === "open" ? "probe" : "normal";
  const reserved = nextState(state, {
    state: "probe_allowed",
    lastAttemptAt: nowIso,
    ...outcomeReceiptUpdates(null, null)
  }, nowIso);
  return Object.freeze({
    allowed: true,
    reason: attemptKind === "probe" ? "probe_reserved" : "normal_attempt_reserved",
    attemptKind,
    state: reserved,
    retryAt: reserved.retryAt
  });
}

function recordProviderBlock(state, failure = {}, options = {}) {
  assertProviderCircuitState(state);
  assertExpectedRevision(state, options.expectedWorkflowRevision);
  assertReservedAttempt(state);
  const safe = sanitizeProviderFailureMeta(failure, { now: options.now, occurredAt: options.now });
  const consecutiveBlocks = state.consecutiveBlocks + 1;
  const cooldownSeconds = computeProviderCooldownSeconds({
    subtype: safe.subtype,
    retryAfterSeconds: safe.retryAfterSeconds,
    consecutiveBlocks
  });
  const openedAt = canonicalInstant(options.now ?? safe.occurredAt, "now");
  const retryAt = new Date(Date.parse(openedAt) + cooldownSeconds * 1000).toISOString();
  return nextState(state, {
    state: "open",
    openedAt,
    retryAt,
    consecutiveBlocks,
    lastFailureSubtype: safe.subtype,
    lastDiagnosticId: safe.diagnosticId,
    lastAttemptAt: state.lastAttemptAt ?? openedAt,
    ...outcomeReceiptUpdates("block", options.outcomeReceiptHash)
  }, openedAt);
}

function refreshProviderAttemptLease(state, options = {}) {
  assertProviderCircuitState(state);
  assertExpectedRevision(state, options.expectedWorkflowRevision);
  assertReservedAttempt(state);
  const nowIso = canonicalInstant(options.now ?? new Date(), "now");
  if (Date.parse(nowIso) < Date.parse(state.updatedAt)) {
    const error = new Error("NAVER provider attempt heartbeat cannot move backwards");
    error.code = "NAVER_PROVIDER_HEARTBEAT_TIME_INVALID";
    error.statusCode = 409;
    throw error;
  }
  return nextState(state, {}, nowIso);
}

function recordProviderSuccess(state, options = {}) {
  assertProviderCircuitState(state);
  assertExpectedRevision(state, options.expectedWorkflowRevision);
  assertReservedAttempt(state);
  const succeededAt = canonicalInstant(options.now ?? new Date(), "now");
  return nextState(state, {
    state: "closed",
    openedAt: null,
    retryAt: null,
    consecutiveBlocks: 0,
    lastFailureSubtype: null,
    lastDiagnosticId: null,
    lastAttemptAt: state.lastAttemptAt ?? succeededAt,
    lastSuccessAt: succeededAt,
    ...outcomeReceiptUpdates("success", options.outcomeReceiptHash)
  }, succeededAt);
}

function releaseProviderAttempt(state, options = {}) {
  assertProviderCircuitState(state);
  assertExpectedRevision(state, options.expectedWorkflowRevision);
  if (state.state !== "probe_allowed") return state;
  const nowIso = canonicalInstant(options.now ?? new Date(), "now");
  if (state.openedAt && state.retryAt && state.consecutiveBlocks > 0) {
    return nextState(state, {
      state: "open",
      ...outcomeReceiptUpdates("release", options.outcomeReceiptHash)
    }, nowIso);
  }
  return nextState(state, {
    state: "closed",
    openedAt: null,
    retryAt: null,
    consecutiveBlocks: 0,
    ...outcomeReceiptUpdates("release", options.outcomeReceiptHash)
  }, nowIso);
}

function providerAvailability(state, options = {}) {
  assertProviderCircuitState(state);
  const nowIso = canonicalInstant(options.now ?? new Date(), "now");
  const attemptLeaseRetryAt = state.state === "probe_allowed"
    ? new Date(Date.parse(state.updatedAt) + PROVIDER_ATTEMPT_LEASE_SECONDS * 1000).toISOString()
    : null;
  const attemptInFlight = Boolean(attemptLeaseRetryAt && Date.parse(attemptLeaseRetryAt) > Date.parse(nowIso));
  const interruptedProbe = state.state === "probe_allowed"
    && Boolean(state.openedAt && state.retryAt && state.consecutiveBlocks > 0);
  const retryAt = attemptInFlight ? attemptLeaseRetryAt : state.retryAt;
  const retryAfterSeconds = retryAt
    ? Math.max(0, Math.ceil((Date.parse(retryAt) - Date.parse(nowIso)) / 1000))
    : 0;
  return Object.freeze({
    providerId: NAVER_PROVIDER_ID,
    available: state.state === "closed" || (state.state === "probe_allowed" && !attemptInFlight && !interruptedProbe),
    coolingDown: state.state === "open" && retryAfterSeconds > 0,
    probeRequired: (state.state === "open" && retryAfterSeconds === 0)
      || (state.state === "probe_allowed" && !attemptInFlight && interruptedProbe),
    attemptInFlight,
    retryAt,
    retryAfterSeconds,
    workflowRevision: state.workflowRevision
  });
}

module.exports = {
  COOLDOWN_POLICY_VERSION,
  DEFAULT_429_COOLDOWN_SECONDS,
  DEFAULT_ACCESS_BLOCK_COOLDOWN_SECONDS,
  FAILURE_SUBTYPES,
  MAX_COOLDOWN_SECONDS,
  NAVER_PROVIDER_ID,
  PROVIDER_ATTEMPT_HEARTBEAT_SECONDS,
  PROVIDER_ATTEMPT_LEASE_SECONDS,
  PROVIDER_HEALTH_SCHEMA_VERSION,
  PROVIDER_STATES,
  PUBLIC_BLOCK_CODE,
  assertProviderCircuitState,
  beginProviderAttempt,
  classifyNaverAccessResponse,
  computeProviderCooldownSeconds,
  createInitialProviderCircuitState,
  parseSafeRetryAfter,
  providerAvailability,
  refreshProviderAttemptLease,
  recordProviderBlock,
  recordProviderSuccess,
  releaseProviderAttempt,
  revisionConflict,
  sanitizeProviderFailureMeta,
  validateProviderCircuitState
};
