"use strict";
const assert = require("node:assert/strict");
const { applyInventoryEvidence, productEvidence } = require("./inventory_estimation.cjs");
const mint = require("./fixtures/mint_20260920.cjs");
const before = JSON.stringify(mint);
const result = applyInventoryEvidence(mint);
assert.equal(JSON.stringify(mint), before, "Original evidence must stay unchanged");
assert.equal(result.inventoryEvidence.physicalRooms.count, 28);
assert.equal(result.weeklyTotalStock, 667, "Use the sum of daily channel quantities, not 21 × 31 or 28 × 31");
assert.equal(result.weeklyTotalSoldOut, 151, "Do not add eight unproven offline bookings");
assert.equal(result.weeklyAdjustedRevenue, 35699000);
assert.equal(result.dayUseWeeklyTotalStock, 81);
assert.equal(result.dayUseWeeklyTotalSoldOut, 3);
assert.equal(result.dayUseWeeklyAdjustedRevenue, 297000);
assert.equal(result.dayUseWeeklyMissingPriceSoldOut, 0, "Closed dates do not become price-missing sales");
assert.equal(result.inventoryEvidence.legacyExcluded.revenue, 3180000);
assert.equal(result.inventoryEvidence.dayUse.rows.length, 31, "Zero-stock days remain visible");
assert.equal(result.inventoryEvidence.lodging.rows.find(r=>r.date==="2026-10-05").sold, 2, "Shared rooms alone do not erase independent overnight bookings");
assert.equal(result.inventoryEvidence.dayUse.rows.find(r=>r.date==="2026-10-05").sold, 2);
assert.equal(applyInventoryEvidence(result), result, "Do not apply corrections twice");
const closed = productEvidence({date:"2026-09-26",stock:0,bookingCount:0,occupiedBookingCount:0,price:0,open:false,listType:"객실별 예약리스트"});
assert.deepEqual([closed.total,closed.sold,closed.missingPriceSoldOut],[0,0,0]);
const shared = productEvidence({date:"2026-09-21",stock:10,bookingCount:2,occupiedBookingCount:3,price:100000,open:true});
assert.deepEqual([shared.total,shared.available,shared.sold,shared.unverifiedOccupied,shared.estimatedRevenue],[10,5,2,3,200000]);
const stockAlreadyReduced = productEvidence({date:"2026-09-21",stock:7,bookingCount:2,occupiedBookingCount:0,price:100000,open:true});
assert.equal(stockAlreadyReduced.sold,2,"Already-reduced stock is not subtracted from reservations again");
assert.equal(productEvidence({stock:null,bookingCount:null,open:false}).observed,false,"Missing provider response is not zero sales");
const priceMissing = productEvidence({stock:5,bookingCount:2,occupiedBookingCount:0,price:null,open:true});
assert.equal(priceMissing.missingPriceSoldOut,2);
assert.equal(priceMissing.estimatedRevenue,0);
const conflict = productEvidence({stock:0,bookingCount:2,price:100000,open:false});
assert.equal(conflict.inventoryConflict,true);
assert.equal(conflict.sold,2,"Retain explicit evidence even when inventory conflicts");
const unknown = applyInventoryEvidence({...mint,placeId:"other"});
assert.equal(unknown.inventoryEvidence.physicalRooms.count,null,"Do not infer physical rooms from max channel stock or product names");
const legacy = { weeklyProductDetails: [{date:"2026-09-20",name:"old",total:5,available:2,soldOut:3}], weeklyTotalSoldOut:3 };
assert.equal(applyInventoryEvidence(legacy),legacy,"Legacy totals alone cannot be upgraded to booking evidence");
assert.equal(applyInventoryEvidence({weeklyProductDetails:[{date:"2026-09-20",name:"데이유즈도 가능한 객실",saleType:"숙박",stock:5,bookingCount:1,price:100000}]}).inventoryEvidence.lodging.sold,1,"Explicit sale type takes precedence over promotional name");
assert.equal(productEvidence({name:"Holiday room",stock:1,bookingCount:1}).kind,"lodging");
assert.equal(productEvidence({name:"대실",stock:1,bookingCount:1}).kind,"dayUse");
assert.equal(productEvidence({stock:" ",bookingCount:false}).observed,false);
const mixed = applyInventoryEvidence({weeklyDays:3,weeklyProductDetails:[
  {date:"2026-09-20",name:"객실",stock:5,bookingCount:1,price:100000},
  {date:"2026-09-22",name:"당일글램핑",stock:null,bookingCount:null,price:null}
],dayUseWeeklyAdjustedRevenue:900});
assert.equal(mixed.inventoryEvidence.dayUse.status,"missing");
assert.equal(mixed.dayUseWeeklyAdjustedRevenue,0,"All-missing day-use evidence must not revive legacy estimated sales");
assert.equal(mixed.inventoryEvidence.lodging.complete,false,"Missing requested dates prevent a complete label");
console.log("inventory estimation: Mint 31-day evidence and shared-room boundaries passed");
