"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
global.fetch = () => { throw new Error("Network calls are forbidden in lodging category UI contract tests"); };
const root = path.resolve(__dirname, "..");
const app = fs.readFileSync(path.join(root, "web", "app.js"), "utf8");
const html = fs.readFileSync(path.join(root, "web", "index.html"), "utf8");
const css = fs.readFileSync(path.join(root, "web", "styles.css"), "utf8");
const server = fs.readFileSync(path.join(root, "scripts", "glamping_app_server.cjs"), "utf8");
assert.match(html, /lodging-category-profile\.js/);
assert.match(app, /lodgingCategoryBadgesHtml/);
assert.match(app, /lodgingCategoryDetailHtml/);
assert.match(app, /lodgingCategorySummaryHtml/);
assert.match(app, /data-company-master-category/);
assert.match(app, /data-manual-primary-category/);
assert.match(app, /data-manual-category-tag/);
assert.match(app, /data-manual-category-note/);
assert.match(app, /manualCategoryOverride/);
assert.match(app, /duplicateReviewStatus/);
assert.match(css, /lodging-category-badges/);
assert.match(css, /@media \(max-width: 390px\)/);
assert.match(css, /focus-visible/);
assert.match(server, /categorySummary: summarizeLodgingCategories/);
assert.match(server, /normalizeCompanyCategory/);
assert.doesNotMatch(app, /스테이폴리오[\s\S]{0,80}privateStay/);
console.log("Lodging category UI/server contract checks passed");
