'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
const net=require('node:net');
const {randomBytes,randomUUID}=require('node:crypto');
const {spawn}=require('node:child_process');
const {createConnectedServer}=require('../customer-portal/connected-server.cjs');
const {createInsightAdminStore}=require('./lib/insight_admin_store.cjs');
async function port(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
test('administrator reservation, hashing, expiry and revocation are persistent and isolated',async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'insight-admin-store-'));let clock=Date.now();const file=path.join(dir,'admin.sqlite');
  let store=createInsightAdminStore({file,now:()=>clock});t.after(()=>store.close());
  const pending=store.reserve('admin','operator');assert.equal(pending.status,'pending');assert.equal(store.reserve('ADMIN','operator').adminId,pending.adminId);
  await assert.rejects(store.login('admin','0914'),{code:'INVALID_LOGIN'});
  await assert.rejects(store.activate(pending.adminId,'0914','0914','operator'),{code:'PASSWORD_POLICY'});
  const password='FixtureAdmin2026!';const outcomes=await Promise.allSettled([store.activate(pending.adminId,password,password,'operator'),store.activate(pending.adminId,password,password,'operator')]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);
  const login=await store.login('admin',password);assert.equal(login.admin.role,'insight_admin');assert.equal(JSON.stringify(login).includes('password_hash'),false);
  store.close();store=createInsightAdminStore({file,now:()=>clock});assert.equal(store.authenticate(login.token).adminId,pending.adminId);
  clock+=8*3600000+1;assert.throws(()=>store.authenticate(login.token),{code:'ADMIN_LOGIN_REQUIRED'});
  const renewed=await store.login('admin',password);store.disable(pending.adminId,'operator');assert.throws(()=>store.authenticate(renewed.token),{code:'ADMIN_LOGIN_REQUIRED'});await assert.rejects(store.login('admin',password),{code:'INVALID_LOGIN'});
  assert.equal((await fs.readFile(file)).includes(Buffer.from(password)),false);
  for(let i=0;i<8;i++)await assert.rejects(store.login('nobody','bad'),{code:'INVALID_LOGIN'});
  await assert.rejects(store.login('nobody','bad'),{code:'RATE_LIMITED'});
});
test('actual DataLab and customer BFF isolate admin privileges, protect provisioning, and retain access over restart',async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'insight-admin-http-'));const backendPort=await port(),frontPort=await port();
  const backend=`http://127.0.0.1:${backendPort}`,origin=`http://127.0.0.1:${frontPort}`,serviceToken=randomBytes(32).toString('hex');
  const env={...Object.fromEntries(Object.entries(process.env).filter(([k])=>['PATH','SYSTEMROOT','WINDIR','TEMP','TMP'].includes(k.toUpperCase()))),PORT:String(backendPort),HOST:'127.0.0.1',DATA_DIR:dir,OUTPUTS_DIR:path.join(dir,'outputs'),CONFIG_DIR:path.join(dir,'config'),GLAMPING_ADMIN_USER:'fixture-central',GLAMPING_ADMIN_PASSWORD:'FixtureCentral2026!',GLAMPING_B2B_USER:'reserved-fixture',GLAMPING_B2B_PASSWORD:'FixtureReserved2026!',TOURISM_VISITOR_MONTHLY_SYNC_ENABLED:'0',TOURISM_DEMAND_STRENGTH_BACKFILL_ENABLED:'0',INSIGHT_CONNECTION_ENABLED:'1',INSIGHT_SERVICE_TOKEN:serviceToken,INSIGHT_SIGNUP_ENABLED:'1'};
  let child;
  async function start(){child=spawn(process.execPath,[path.join(__dirname,'glamping_app_server.cjs')],{env,stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Fixture startup timeout')),15000);child.stdout.on('data',c=>{if(String(c).includes('Lodging datalab beta app running')){clearTimeout(timeout);resolve();}});child.once('exit',code=>{clearTimeout(timeout);reject(Error('Fixture exited '+code));});});}
  async function stop(){if(child&&!child.killed)await new Promise(r=>{child.once('exit',r);child.kill();});}
  t.after(stop);await start();const front=createConnectedServer({origin,backend,serviceToken});await new Promise(r=>front.listen(frontPort,'127.0.0.1',r));t.after(()=>{front.closeAllConnections();front.close();});
  const request=(route,payload,headers={})=>fetch(origin+route,{method:payload?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',...headers},...(payload?{body:JSON.stringify(payload)}:{})});
  const prefix='/api/insight-admin/v1';
  assert.equal((await fetch(origin+'/admin')).status,200);
  assert.equal((await request(prefix+'/customers')).status,401);
  const unauth=await fetch(backend+'/api/admin/insight-admin-accounts',{headers:{Accept:'application/json'},redirect:'manual'});assert.ok([302,401,403].includes(unauth.status));
  assert.equal((await fetch(backend+'/api/insight/v1/admin/me')).status,401);
  const centralLogin=async()=>{const r=await fetch(backend+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'fixture-central',password:env.GLAMPING_ADMIN_PASSWORD})});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];};
  let centralCookie=await centralLogin();
  const provision=(p,extra={})=>fetch(backend+'/api/admin/insight-admin-accounts',{method:p?'POST':'GET',headers:{Cookie:centralCookie,Origin:backend,'Content-Type':'application/json',...extra},...(p?{body:JSON.stringify(p)}:{})});
  const reserve=await provision({action:'reserve',username:'admin'});assert.equal(reserve.status,200);const pending=(await reserve.json()).accounts[0];
  assert.equal(pending.status,'pending');const password='FixtureInsight2026!';
  assert.equal((await request(prefix+'/auth/login',{username:'admin',password})).status,401);
  assert.equal((await provision({action:'activate',adminId:pending.adminId,password,passwordConfirm:password},{Origin:'https://untrusted.invalid'})).status,403);
  assert.equal((await provision({action:'activate',adminId:pending.adminId,password,passwordConfirm:password})).status,200);
  for(const p of ['/insight-admin-accounts','/insight-admin-accounts.js','/insight-admin-accounts.css'])assert.equal((await fetch(backend+p,{headers:{Cookie:centralCookie}})).status,200);
  assert.equal((await request(prefix+'/auth/login',{username:'admin',password,role:'admin'})).status,400);
  assert.equal((await request(prefix+'/auth/login',{username:'admin',password},{Origin:'https://untrusted.invalid'})).status,403);
  const logged=await request(prefix+'/auth/login',{username:'admin',password});assert.equal(logged.status,200);const loggedBody=await logged.json();const adminCookie=logged.headers.get('set-cookie').split(';')[0];
  assert.match(adminCookie,/^insight_local_admin=/);assert.match(logged.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.equal(loggedBody.token,undefined);assert.equal(JSON.stringify(loggedBody).includes(serviceToken),false);
  const adminHeaders={Cookie:adminCookie,'X-CSRF-Token':loggedBody.csrfToken};
  const config=await(await request('/api/customer/v1/config')).json();
  const sign=await request('/api/customer/v1/auth/signup',{username:'fixture-customer',password:'FixtureCustomer2026!',passwordConfirm:'FixtureCustomer2026!',phone:'01000000000',email:'fixture@example.invalid',agreeTerms:true,agreePrivacy:true,confirmAge:true,termsVersion:config.termsVersion,privacyVersion:config.privacyVersion,businessStatus:'planning'});assert.equal(sign.status,200);const customer=(await sign.json()).customer;const customerCookie=sign.headers.get('set-cookie').split(';')[0];
  assert.equal((await request(prefix+'/customers',null,{Cookie:customerCookie})).status,401);
  assert.equal((await request('/api/customer/v1/me',null,adminHeaders)).status,401);
  assert.equal((await request('/api/customer/v1/auth/login',{username:'admin',password})).status,401);
  assert.equal((await request(prefix+'/customers',null,adminHeaders)).status,200);
  const route=prefix+'/customers/'+customer.customerId;
  const cmd={action:'entitlements',revision:customer.revision,requestKey:randomUUID(),payload:{competitorLimit:5,interestRegionLimit:2,reason:'fixture approval'}};
  assert.equal((await request(route+'/commands',cmd,{Cookie:adminCookie})).status,403);
  assert.equal((await request(route+'/commands',cmd,adminHeaders)).status,200);
  assert.equal((await request(route+'/commands',{...cmd,requestKey:randomUUID(),action:'prepare-data'},adminHeaders)).status,409);
  assert.equal((await request(route+'/preparation-dispatch',{},adminHeaders)).status,404);
  assert.equal((await request('/api/crawl',{},adminHeaders)).status,404);
  assert.equal((await request('/api/admin/insight-admin-accounts',{},adminHeaders)).status,404);
  const state=await(await request(route,null,adminHeaders)).json();assert.equal(state.customer.entitlements.competitorLimit,5);assert.equal(state.history[0].actor,pending.adminId);
  await stop();await start();assert.equal((await request(prefix+'/me',null,adminHeaders)).status,200);
  centralCookie=await centralLogin();assert.equal((await provision({action:'disable',adminId:pending.adminId})).status,200);
  assert.equal((await request(prefix+'/me',null,adminHeaders)).status,401);assert.equal((await request(prefix+'/auth/login',{username:'admin',password})).status,401);
});
